#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/../test_env.sh
EXECUTOR="$(atf_get_srcdir)/../../executor-scripts/linux/static"
FIXTURES="$(atf_get_srcdir)/../fixtures"

tests_init up down

up_body() {
	export IFACE=eth0 PHASE=up MOCK=echo INTERFACES_FILE="$FIXTURES/static-eth0.interfaces"
	atf_check -s exit:0 \
		-o match:'addr add 203.0.113.2/24 dev eth0' \
		-o match:'addr add 2001:db8:1000:2::2/64 dev eth0' \
		-o match:'route add default via 203.0.113.1' \
		-o match:'route add default via 2001:db8:1000:2::1' \
		${EXECUTOR}
}

down_body() {
	export IFACE=eth0 PHASE=down MOCK=echo INTERFACES_FILE="$FIXTURES/static-eth0.interfaces"
	atf_check -s exit:0 \
		-o match:'addr del 203.0.113.2/24 dev eth0' \
		-o match:'addr del 2001:db8:1000:2::2/64 dev eth0' \
		-o match:'route del default via 203.0.113.1' \
		-o match:'route del default via 2001:db8:1000:2::1' \
		${EXECUTOR}
}
