#!/bin/sh
[ -z "$VERBOSE" ] || set -x

: "${PROCFS_ROOT:=/proc}"

yesno() {
        case "$1" in
        yes|1)  echo 1 ;;
        *)      echo 0 ;;
        esac
}

case "$PHASE" in
up)
	if [ -n "$IF_IPV6_AUTOCONF" -a -e "$PROCFS_ROOT/sys/net/ipv6/conf/${IFACE}/autoconf" ]; then
		printf '%s\n' "$(yesno "${IF_IPV6_AUTOCONF}")" > "$PROCFS_ROOT/sys/net/ipv6/conf/${IFACE}/autoconf"
	fi

	if [ -n "$IF_IPV6_ACCEPT_RA" -a -e "$PROCFS_ROOT/sys/net/ipv6/conf/${IFACE}/accept_ra" ]; then
		printf '%s\n' "${IF_IPV6_ACCEPT_RA}" > "$PROCFS_ROOT/sys/net/ipv6/conf/${IFACE}/accept_ra"
	fi

	if [ -n "$IF_IPV6_DAD_TRANSMITS" -a -e "$PROCFS_ROOT/sys/net/ipv6/conf/${IFACE}/dad_transmits" ]; then
		printf '%s\n' "${IF_IPV6_DAD_TRANSMITS}" > "$PROCFS_ROOT/sys/net/ipv6/conf/${IFACE}/dad_transmits"
	fi

	if [ -n "$IF_IPV6_OPTIMISTIC_DAD" -a -e "/proc/sys/net/ipv6/conf/${IFACE}/optimistic_dad" ]; then
		${MOCK} echo $(yesno ${IF_IPV6_OPTIMISTIC_DAD}) > "/proc/sys/net/ipv6/conf/${IFACE}/optimistic_dad"
	fi
	;;
esac
