#!/bin/sh
# Executor for advanced GRE tunnel management.

is_busybox() {                                                                   
        local a                                                                  
        for a in $(ls -l $(which ip)); do                                        
                if [ "$(echo $a|grep busybox)" == "busybox" ]; then                        
                        return 0                                                 
                fi                                                                                                               
        done
	return 1
} 

[ -z "$IF_GRE_LOCAL" ] && exit 1
[ -z "$IF_GRE_MODE" ] && IF_GRE_MODE="gre"

COMMAND="link"
FAMILY="-4"
[ "$IF_GRE_MODE" = "ip6gre" ] && FAMILY="-6"

TYP="type"
if is_busybox; then
	TYP="mode"
fi

PARAMS="$TYP $IF_GRE_MODE local '$IF_GRE_LOCAL'"
[ -n "$IF_GRE_REMOTE" ] && PARAMS="$PARAMS remote '$IF_GRE_REMOTE'"
[ -n "$IF_GRE_TTL" ] && PARAMS="$PARAMS ttl '$IF_GRE_TTL'"
[ -n "$IF_GRE_KEY" ] && PARAMS="$PARAMS key '$IF_GRE_KEY'"
[ -n "$IF_GRE_FLAGS" ] && PARAMS="$PARAMS $IF_GRE_FLAGS"

[ -n "$PARAMS" ] || exit 0

case "$PHASE" in
create)
	${MOCK} eval ip $FAMILY $COMMAND add $IFACE $PARAMS
	;;
destroy)
	${MOCK} ip $FAMILY $COMMAND del $IFACE
	;;
depend)
	echo "$IF_GRE_DEV"
	;;
esac
