#!/bin/sh

start() {
	echo 1 > /proc/sys/net/ipv6/conf/$IFACE/accept_ra
}

stop() {
	echo 0 > /proc/sys/net/ipv6/conf/$IFACE/accept_ra
}

[ -z "$VERBOSE" ] || set -x

case "$PHASE" in
up) start $impl ;;
down) stop $impl ;;
*) ;;
esac
