#!/bin/sh
start() {
	${MOCK} /bin/sh -c "echo 2 > /proc/sys/net/ipv6/conf/$IFACE/use_tempaddr"
}

stop() {
	${MOCK} /bin/sh -c "echo 0 > /proc/sys/net/ipv6/conf/$IFACE/use_tempaddr"
}

[ -z "$VERBOSE" ] || set -x

case "$PHASE" in
pre-up) start $impl ;;
pre-down) stop $impl ;;
*) ;;
esac
