#!/bin/sh
[ -n "$VERBOSE" ] && set -x

case "$PHASE" in
create)
	if [ -n "$IF_WIREGUARD_HOME_NETNS" ]; then
		# Create interface in the configured network namespace
		${MOCK} ip -n "$IF_WIREGUARD_HOME_NETNS" link add "$IFACE" type wireguard
		${MOCK} ip -n "$IF_WIREGUARD_HOME_NETNS" link set "$IFACE" netns $$
	else
		${MOCK} ip link add "$IFACE" type wireguard
	fi
	;;
pre-up)
	: "${IF_WIREGUARD_CONFIG_PATH:=/etc/wireguard/"$IFACE".conf}"

	${MOCK} export WG_ENDPOINT_RESOLUTION_RETRIES="${IF_WG_ENDPOINT_RESOLUTION_RETRIES:-15}"
	${MOCK} wg setconf "$IFACE" "$IF_WIREGUARD_CONFIG_PATH"
	;;
destroy)
	${MOCK} ip link delete dev "$IFACE"
	;;
esac
