#!/bin/sh
[ -n "$VERBOSE" ] && set -x

case "$PHASE" in
create)
	${MOCK} ip link add "$IFACE" type wireguard
	;;
pre-up)
	: "${IF_WIREGUARD_CONFIG_PATH:=/etc/wireguard/"$IFACE".conf}"

	${MOCK} export WG_ENDPOINT_RESOLUTION_RETRIES="${IF_WG_ENDPOINT_RESOLUTION_RETRIES:-15}"
	${MOCK} wg setconf "$IFACE" "$IF_WIREGUARD_CONFIG_PATH"
	;;
destroy)
	${MOCK} ip link delete dev "$IFACE"
	;;
esac
