#!/bin/sh
[ -n "$VERBOSE" ] && set -x

case "$PHASE" in
create)
	${MOCK} export WG_ENDPOINT_RESOLUTION_RETRIES="${IF_WG_ENDPOINT_RESOLUTION_RETRIES:-15}"
	${MOCK} wg-quick up $IFACE
	;;
destroy)
	${MOCK} wg-quick down $IFACE
	;;
esac
